version: "3"
services:
  opentelemetry-collector:
    image: "otel/opentelemetry-collector-contrib:0.121.0"
    ports:
      - "127.0.0.1:4317:4317"
      - "127.0.0.1:4318:4318"
      - "127.0.0.1:55679:55679"
